### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [HTTP] Internal Server Error

### ISSUE THREAD

**Issue by reteps** [powerapi/powerapi-php#11]
```Fatal error: Uncaught SoapFault exception: [HTTP] Internal Server Error in /Users/Peter/repos/powerphp/vendor/zendframework/zend-soap/src/Client.php:994
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://cms.pow...', 'http://publicpo...', 2, 0)
#1 /Users/Peter/repos/powerphp/vendor/zendframework/zend-soap/src/Client.php(994): call_user_func(Array, '<?xml version="...', 'https://cms.pow...', 'http://publicpo...', 2, 0)
#2 [internal function]: Zend\Soap\Client->_doRequest(Object(Zend\Soap\Client\Common), '<?xml version="...', 'https://cms.pow...', 'http://publicpo...', 2, 0)
#3 /Users/Peter/repos/powerphp/vendor/zendframework/zend-soap/src/Client/Common.php(57): call_user_func(Array, Object(Zend\Soap\Client\Common), '<?xml version="...', 'https://cms.pow...', 'http://publicpo...', 2, 0)
#4 [internal function]: Zend\Soap\Client\Common->__doRequest('<?xml version="...', 'https://cms.pow...', 'http://publicpo...', 2, 0)
#5 /Users/Peter/repos/powerphp/vendor/zendframework/zend-soap/src/C in /Users/Peter/repos/powerphp/vendor/zendframework/zend-soap/src/Client.php on line 994```

my code: 

```
#!/usr/bin/env php 
<?php
require_once 'vendor/autoload.php'; // composer autoloader

try {
    $student = PowerAPI\PowerAPI::authenticate("https://cms.powerschool.com/public/", "username", "password");
} catch (PowerAPI\Exceptions\Authentication $e) {
    die('Something went wrong! '.$e->getMessage());
}

foreach ($student->sections as $section) {
    echo $section->name."\n";
}
```

**Comment by reteps** [comment]
never mind wrong url

**Comment by phlume** [comment]
Lol... I was like. Whoa. Way out of my league... wtf is this?! All good.
Happy debugging.

-c

**Comment by reteps** [comment]
lol i'm trying to convert your api into python, is there any way you can help me out?
